"""add new expense type

Revision ID: 80e871b9828c
Revises: 4b5c6d7e8f9a
Create Date: 2025-12-25 14:15:51.587286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "80e871b9828c"
down_revision: Union[str, None] = "4b5c6d7e8f9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses",
        "expense_type",
        existing_type=sa.VARCHAR(length=20),
        server_default="expense",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses",
        "expense_type",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'expense'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
