"""add_cascade_delete_to_splits

Revision ID: 45435a9d7d71
Revises: 1a13dea6bda1
Create Date: 2025-12-25 00:25:40.053100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45435a9d7d71'
down_revision: Union[str, None] = '1a13dea6bda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('splits_expense_id_fkey', 'splits', type_='foreignkey')
    op.create_foreign_key(None, 'splits', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'splits', type_='foreignkey')
    op.create_foreign_key('splits_expense_id_fkey', 'splits', 'expenses', ['expense_id'], ['id'])
    # ### end Alembic commands ###

