"""create expense type

Revision ID: 3484846916ab
Revises: 80e871b9828c
Create Date: 2025-12-25 14:19:33.644200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3484846916ab"
down_revision: Union[str, None] = "80e871b9828c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE expenses e
        SET 
            expense_type = 'expense'
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
