"""add trip invite allow_claim

Revision ID: 357420a9a2c4
Revises: add_trip_invites
Create Date: 2025-12-30 10:36:21.114487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "357420a9a2c4"
down_revision: Union[str, None] = "add_trip_invites"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses",
        "expense_type",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "member_debts",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True,
    )
    op.alter_column(
        "member_debts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "member_debts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "trip_invites",
        sa.Column(
            "allow_claim", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    op.alter_column(
        "trip_invites",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("idx_trip_invites_code", table_name="trip_invites")
    op.drop_index("idx_trip_invites_trip_id", table_name="trip_invites")
    op.drop_constraint("trip_invites_code_key", "trip_invites", type_="unique")
    op.create_index(op.f("ix_trip_invites_code"), "trip_invites", ["code"], unique=True)
    op.create_index(
        op.f("ix_trip_invites_trip_id"), "trip_invites", ["trip_id"], unique=False
    )
    op.drop_constraint("trip_invites_trip_id_fkey", "trip_invites", type_="foreignkey")
    op.create_foreign_key(None, "trip_invites", "trips", ["trip_id"], ["id"])
    op.alter_column(
        "trip_members",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "trip_members",
        "total_owed_base",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        "trip_members",
        "total_owed_to_base",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        server_default=None,
        nullable=True,
    )
    op.drop_index("idx_trip_members_status", table_name="trip_members")
    op.alter_column(
        "trips",
        "simplify_debts",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "trips",
        "total_spent",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        "trips",
        "expense_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trips",
        "expense_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "trips",
        "total_spent",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        server_default=sa.text("0.0"),
        nullable=False,
    )
    op.alter_column(
        "trips",
        "simplify_debts",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.create_index("idx_trip_members_status", "trip_members", ["status"], unique=False)
    op.alter_column(
        "trip_members",
        "total_owed_to_base",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        server_default=sa.text("0.0"),
        nullable=False,
    )
    op.alter_column(
        "trip_members",
        "total_owed_base",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        server_default=sa.text("0.0"),
        nullable=False,
    )
    op.alter_column(
        "trip_members",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'active'::character varying"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "trip_invites", type_="foreignkey")
    op.create_foreign_key(
        "trip_invites_trip_id_fkey",
        "trip_invites",
        "trips",
        ["trip_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_trip_invites_trip_id"), table_name="trip_invites")
    op.drop_index(op.f("ix_trip_invites_code"), table_name="trip_invites")
    op.create_unique_constraint(
        "trip_invites_code_key",
        "trip_invites",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        "idx_trip_invites_trip_id", "trip_invites", ["trip_id"], unique=False
    )
    op.create_index("idx_trip_invites_code", "trip_invites", ["code"], unique=False)
    op.alter_column(
        "trip_invites",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_column("trip_invites", "allow_claim")
    op.alter_column(
        "member_debts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "member_debts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "member_debts",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
    )
    op.alter_column(
        "expenses",
        "expense_type",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'expense'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
